"""Initial models

Revision ID: 0ad7bd01fa81
Revises: 
Create Date: 2017-04-28 22:37:07.857460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad7bd01fa81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('asset', 'liablility', 'equity', 'income', 'expense'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_units',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('local_currency', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('iso_code')
    )
    op.create_table('metrics',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('accounting_period', sa.String(length=50), nullable=False),
    sa.Column('business_unit', sa.String(length=50), nullable=False),
    sa.Column('driver', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['accounting_period'], ['accounting_periods.id'], ),
    sa.ForeignKeyConstraint(['business_unit'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['driver'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['scenario'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('account', 'accounting_period', 'business_unit', 'driver', 'currency', 'scenario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('exchange_rates')
    op.drop_table('scenarios')
    op.drop_table('drivers')
    op.drop_table('currencies')
    op.drop_table('business_units')
    op.drop_table('accounts')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
